### ISSUE TITLE
Benchmark for Python vs. Data Science

### ISSUE THREAD

**Issue by menewman** [CodeSignal/dockerfiles#150]
Splitting from discussion here:
https://github.com/CodeSignal/dockerfiles/pull/147#issuecomment-628486048

I know we talked about this a bunch but I don't think there was an issue to track the follow-up. So, creating it so we don't lose track of it.

Let's do benchmark in the scope of this task and create a new task later if we will decide to go with a new dockerfile solution.

**Comment by eduard-piliposyan** [comment]
Let's do some benchmarking to find out that there are significant performance differences or not.

**Comment by ArDrambyan** [comment]
I made some benchmarking and here are the results:
I executed simple `print 'Hello'` code without any imports
1. using codesignal/python:v5.6 (without new libs), it takes 0.5-0.7s with docker pool and 1-1.5s without docker pool
2. using codesignal/python:v5.6 (without new libs), it takes 3-3.4s with docker pool and 3.5-4s without docker pool
Cause docker pool optimizes only docker start time I think the image's size didn't affect start time too much, but the code execution time significantly increased. I think it is because of conda's environment, which is used for execution. Also, I noticed that docker removing time is also increased and it can hit overall coderunner's performance.

**Comment by menewman** [comment]
I'm going to assume that the 2nd number is from the example _with_ new libs and the 1st number is from the example without, although both 1 and 2 say "codesignal/python:v5.6 (without new libs)" above!

Very interesting finding, esp. if this will make a significant difference even with Docker pools.

**Comment by ArDrambyan** [comment]
the second one should be codesignal/python:v5.8 and with new libs
