### ISSUE TITLE
Update haskell image to support new Ubuntu version

### ISSUE THREAD

**Issue by ArDrambyan** [CodeSignal/dockerfiles#245]

**Comment by menewman** [comment]
I did start looking at this but will put it back for now since I'm not sure I'll have time to finish the investigation today. I tried upgrading and there seems to be a failure in building `aeson` (running out of memory?) when upgrading Haskell & Cabal versions, but when only updating the base there's an issue finding `ghc-8.8.1`. Probably requires a little more investigation on what's different (should we pin aeson version? Install Haskell differently?)
