### ISSUE TITLE
Questions about the Java environment

### ISSUE THREAD

**Issue by RanX12** [CodeSignal/dockerfiles#278]
Regarding fastxml in the Java environment, I want to support fastxml in my Java Docker image (import com.fasterxml.jackson.*;), but I can’t succeed now. I think your website is doing very well, so I want to ask about it , How can I write in my Dockerfile to make my image support fasterxml?

thx...

my Dockerfile: 
![image](https://user-images.githubusercontent.com/46048444/105811653-ea6c9200-5fe7-11eb-930b-17035b9a2e26.png)

my java code:
![image](https://user-images.githubusercontent.com/46048444/105811496-b2fde580-5fe7-11eb-89f6-43120679a888.png)
![image](https://user-images.githubusercontent.com/46048444/105811526-be511100-5fe7-11eb-801e-986eef3a3165.png)

**Comment by menewman** [comment]
Hi @RanX12 - I'm going to close this issue since our issue tracker is for tracking features or bugs in this repo, and this is a request for help outside of our repository -- however, I think this commit fairly succinctly shows two ways of adding this kind of dependency:
https://github.com/CodeSignal/dockerfiles/commit/384c4fe2703ca9b14f2ba7726872c62a7f24b9b3#diff-2c3cd63eeda6d94e4ac3cc5a0493362bc97cd5f8fa694aea346ee2baf6cec5cb

The before state shows how the dependences can simply be installed in Ubuntu; the after state shows how they can be installed using Gradle (we would recommend the latter here).
