### ISSUE TITLE
Create a Docker image for automated UI tests

### ISSUE THREAD

**Issue by menewman** [CodeSignal/dockerfiles#63]
https://app.asana.com/0/417895759505117/1132358108136274/f

Preferably not Galen. ~Needs Java, Selenium, some kind of driver -- WebdriverIO is fine, especially since we have experience with it already and it's a JS wrapper (no Java is great, and the sync API is nice too).~

~Consider the kinds of setup we do to get WebdriverIO running on CircleCI -- the need here is similar.~

Maybe need to use Puppeteer? There is an example of what FB is trying to accomplish linked in the Asana task.

**Comment by artahian** [comment]
@Albinutte @menewman after further investigation I'm more and more confident that WebDriver doesn't provide a way to inject scripts before the page load. This, of course, can be done differently, by injecting another script along with our preview script that is used to stream logs and errors from within the iframe, but I really don't want to go through that route because it involves a lot of guessing (i.e. which files the script should be injected, and where) and spreading the testing logic outside of the coderunner.

During my investigating I spent more than 2 hours with WebDriver without any luck, while It took me 5 minutes to setup a Node project with puppeteer based on the example here - https://gist.github.com/artahian/ca0366dadf1fc82dde369deb6123affa
which was actually catching tracking calls as necessary.

I still think that WebDriver is a really solid approach that we should use by default for other frontend tasks where the tests are focused on the behavior rather than checking for function calls on the code level, but for this task specifically I assume it shouldn't be hard to simply set up puppeteer (and maybe sinon) in the same docker image and keep our options open for other frontend testing frameworks if necessary.

**Comment by menewman** [comment]
I'm okay with using Puppeteer instead of Webdriver (for now) and eventually in addition to some version of Selenium/Webdriver. I think there's a lot of sense in using the tool that's the best fit for our purpose here, and my initial drafts of these issues were based on the assumption that the tests needed to be automated browser/user tests, since I hadn't yet seen FB's Puppeteer script.

I think it would be nice to try to do browser tests in a way where we don't have to create an entirely different task type to run Webdriver tests vs. Puppeteer tests, if possible... but that doesn't preclude separate Docker images.

**Comment by artahian** [comment]
Yeah, ideally it should be differentiated only by the testingTool property or something similar. Also, if all the testing tools that we use are NodeJS based and are consistent in their output format it might even work out of the box without having to write an adapter maybe?

**Comment by menewman** [comment]
One can dream.

**Comment by artahian** [comment]
@Albinutte, for more context - puppeteer npm package seems to install Chromium on its own, so it most probably isn't even dependent on any external browsers that need to be installed separately. Also, it runs in headless mode by default, so I think it shouldn't be necessary to configure `Xvfb` and similar display related properties for it to work like it is usually done for Webdriver.
